# .github/workflows/cypress.yml
name: Cypress + Relatório

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instala dependências
        run: npm install

      - name: Instala Mochawesome
        run: npm install --save-dev mochawesome mochawesome-merge mochawesome-report-generator

      - name: Roda Cypress com relatório
        run: npx cypress run --reporter mochawesome/src/mochawesome

      - name: Gera relatório HTML
        if: always()
        run: |
          npx mochawesome-merge "cypress/reports/mochawesome/*.json" > cypress/reports/full-report.json
          npx marge cypress/reports/full-report.json --reportDir cypress/reports/results.html --inline --charts

      - name: Upload do relatório completo
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-cypress-${{ github.run_number }}
          path: |
            cypress/reports/html
          retention-days: 1